### PR TITLE
Checkstyle findbugs pmd

### PR DESCRIPTION
**Pull request by jorisoudejans**
Added support for these three static analysis tools. For there is no PMD SBT plug-in (not a working one), PMD must be consulted locally.

### CODE REVIEW

**Comment by hiddely** [comment]
Looks good!

**Comment by feclist** [comment]
Awesome. There are conflicts with this branch, these have to be fixed I bet  :(

**Comment by jorisoudejans** [comment]
Yeah I can fix the conflicts if ya'll agree on merging

**Comment by feclist** [comment]
:+1:

**Comment by skoppers** [comment]
:+1:

**Pull request merged**
