### PR TITLE
Clientside script api

### PR DESCRIPTION
**Pull request by hiddely**
While this changes the UI and removes old typescript classes, it shows the power of the http api interacting with the script api on the server!

### CODE REVIEW

**Comment by jorisoudejans** [comment]
Seems good, after we've incorporated checkstyle etc in SBT, all static analysis tools will have to be 100% conformed to. Keep that in mind...

**Comment by hlycklama** [comment]
Sets up basic typescript implementation on client side of scripting api

**Comment by skoppers** [comment]
Looks good! :+1:

**Comment by feclist** [comment]
Lookin' gud. The server side api looks nice, just what we needed to really kick off with everything.

**Pull request merged**
