### PR TITLE
Add director html

### PR DESCRIPTION
**Pull request by feclist**
2 of the 3 views are build. The 3rd one is going to be the livestream of cameras. This has to be implemented along a new camera object and database table that goes with it. We also need to build a current camera object on the server/db side and we need to build listeners on the clients for changes in presets and actions for example.

### CODE REVIEW

**Comment by jorisoudejans** [comment]
The result is quite different from the design. Why is that?

**Comment by jorisoudejans** [comment]
And what is the Script list for?

**Comment by feclist** [comment]
The script list was used for testing purposes. To see if everything worked. That is not part of the final design and I will remove it shortly. I haven't yet worked on the colors and the horizontal action bar and next view button aren't done yet. 

We also need to find a good balance for the preset tiles. We need to take sizes etc into account, it needs some fine tuning. 

I also changed the order of the action text since we still need to figure out how and if we want to make those actions do a countdown. For now it seemed most important to me that you can see what the action is supposed to do. And the estimated time and which preset the action belongs to are details.

What other things do you find different from the initial design? I could change some stuff to preference, that's no prob

**Comment by jorisoudejans** [comment]
Ah allright, thanks for the exp ;). Is it too much work for now to give the preset view the green background, inset shadow and 3-col layout?

**Comment by feclist** [comment]
Did what you asked joris, also added a quick camera view mock :)

**Comment by jorisoudejans** [comment]
Awesome!! Shaping up real nice. Inset shadow is 5px rgba(0,0,0,89) (no offsets). I'll add this real quick

**Comment by jorisoudejans** [comment]
Application.java seems a bit bloated. Maybe create a seperate method for the dummy content creation?

**Pull request merged**
